added FCM
GEPTON-INFOTECH/chinchilla pull request #28
Opened 2021-12-27 08:44 UTC by jaynit1106

# Description

added FCM to the project

Fixes #25

2021-12-27 12:03 UTC, abhibhaw requested changes
Just minor changes, review once. Also please attach a few notification ss in this pr for reference

2021-12-27 12:03 UTC, abhibhaw commented on customer_app/lib/services/graphql_services.dart
> +import 'package:get/get_core/src/get_main.dart';
Again just importing get/get.dart is suffiecient Multiple imports should be avoided

2021-12-29 12:59 UTC, abhibhaw requested changes

2021-12-29 12:59 UTC, abhibhaw commented on customer_app/lib/views/screens/home/customer_app.dart
> +  _changeData(String msg)=>print(msg);
Unnecessary print statement. Can be removed ig?

2021-12-29 15:17 UTC, jaynit1106 commented on customer_app/lib/views/screens/home/customer_app.dart
> +  _changeData(String msg)=>print(msg);
they are for foreground notification

2021-12-29 21:08 UTC, abhibhaw commented
TODO: #29

2021-12-29 21:09 UTC, abhibhaw approved these changes
lgtm

2021-12-29 21:09 UTC, abhibhaw commented
Also a suggestion, Please write better commit messages.

2021-12-29 21:09 UTC, merged