added FCM listener for foreground state
GEPTON-INFOTECH/chinchilla pull request #32
Opened 2022-01-05 12:38 UTC by jaynit1106

added Snack bar for foreground state

Fixes #29 

Some Screenshots:-
![WhatsApp Image 2022-01-04 at 4 05 56 PM (1)](https://user-images.githubusercontent.com/77606730/148218818-1efb74cb-401f-4e5c-ade6-afa9a7e0a32b.jpeg)

2022-01-05 12:46 UTC, abhibhaw requested changes

2022-01-05 12:46 UTC, abhibhaw commented on customer_app/lib/views/screens/home/customer_app.dart
> +    launchSnack("Gepton", msg);
Accidentally u hard-coded the snack title

2022-01-05 13:01 UTC, jaynit1106 commented on customer_app/lib/views/screens/home/customer_app.dart
> +    launchSnack("Gepton", msg);
Done

2022-01-06 15:55 UTC, abhibhaw approved these changes
lgtm

2022-01-06 15:56 UTC, merged