redesigned OTP page
GEPTON-INFOTECH/chinchilla pull request #33
Opened 2022-01-07 16:42 UTC by jaynit1106

redesigned the OTP page and fixed some error

Fixes #26 

some screenshots:-
![WhatsApp Image 2022-01-07 at 10 09 55 PM](https://user-images.githubusercontent.com/77606730/148576568-8aabd81c-29a4-437e-8b31-df84bda63b13.jpeg)

2022-01-09 16:45 UTC, abhibhaw requested changes
OTP text-field submit button should be inactive if all fields are not filled. Also a better error handling is required. We can't just display the error msg by firebase, It should be human readable text. Check for firebase error code and accordingly display simple text.

A few minor changes, rest awesome work.. Kuddo's to you 🎉

2022-01-09 16:45 UTC, abhibhaw commented on customer_app/lib/views/screens/login_flow/OTP_screen.dart
> +class otpScreen extends StatelessWidget {
Class name should always be Capitalize

2022-01-09 16:45 UTC, abhibhaw commented on customer_app/lib/views/screens/login_flow/OTP_screen.dart
> +            Text("My Code is",
Change it to My OTP is

2022-01-09 16:45 UTC, abhibhaw commented on customer_app/lib/views/screens/login_flow/OTP_screen.dart
> +                fontSize: 35
All sizing should be dynamic, No hardcoding

2022-01-09 16:45 UTC, abhibhaw commented on customer_app/lib/views/screens/login_flow/OTP_screen.dart
> +                  onPressed: (){},
Functionality ??

2022-01-09 16:45 UTC, abhibhaw commented on customer_app/lib/views/screens/login_flow/OTP_screen.dart
> +                      fontSize: 20,
No hardcoding again

2022-01-09 16:45 UTC, abhibhaw commented on customer_app/lib/views/screens/login_flow/login_screen.dart
> +            inputFormatters: [new LengthLimitingTextInputFormatter(10)],
It should check for exact 10 not less than 10

2022-01-10 06:01 UTC, jaynit1106 commented on customer_app/lib/views/screens/login_flow/OTP_screen.dart
> +class otpScreen extends StatelessWidget {
done

2022-01-11 08:20 UTC, abhibhaw requested changes
minor fixes

2022-01-11 08:20 UTC, abhibhaw commented on customer_app/lib/controllers/authController.dart
> +      launchSnack('Error',"Invalid OTP");
It can't be this error every time. Check for error code and the add logical texts

2022-01-11 08:20 UTC, abhibhaw commented on customer_app/lib/views/screens/login_flow/OTP_screen.dart
> +                      launchSnack("Error", "Invalid OTP");
Better

2022-01-11 08:20 UTC, abhibhaw commented on customer_app/lib/views/screens/login_flow/login_screen.dart
> +                      launchSnack("Error", "Invalid Phone Number");
OP

2022-01-11 08:20 UTC, abhibhaw commented on customer_app/lib/views/screens/login_flow/login_screen.dart
> +                      _authController.login(_phoneController.text);
In this function as well there's a snackbar stating the errors. Please handle that as well

2022-01-11 11:49 UTC, jaynit1106 commented on customer_app/lib/views/screens/login_flow/OTP_screen.dart
> +                      launchSnack("Error", "Invalid OTP");
error will be always invalid verification code

2022-01-12 17:05 UTC, abhibhaw approved these changes
lgtm

2022-01-12 17:10 UTC, merged